[2018-11-13 14:39:16,513 INFO 24924 Log.py 25] - C:/Users/admin/Desktop/python/webchat/logs/py_webchat.log
[2018-11-13 16:03:26,304 ERROR 27148 dbutil.py 58] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, wx_msg_keyword, wx_msg_type, wx_msg_value
[2018-11-13 16:03:29,528 ERROR 20852 dbutil.py 58] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, wx_msg_keyword, wx_msg_type, wx_msg_value
[2018-11-13 16:04:22,455 ERROR 26900 dbutil.py 58] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, wx_msg_keyword, wx_msg_type, wx_msg_value
[2018-11-13 16:04:58,206 ERROR 27440 dbutil.py 58] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, wx_msg_keyword, wx_msg_type, wx_msg_value
[2018-11-13 16:16:45,713 WARNING 27468 base.py 152] - Not Found: /favicon.ico
[2018-11-14 15:31:29,279 ERROR 41352 dbutil.py 44] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, tb_appid, tb_appname, tb_secret, tb_token
[2018-11-14 15:31:58,252 ERROR 22996 dbutil.py 44] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, tb_appid, tb_appname, tb_secret, tb_token
[2018-11-14 15:32:24,278 ERROR 41892 dbutil.py 44] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, tb_appid, tb_appname, tb_secret, tb_token
[2018-11-14 15:32:32,424 ERROR 39956 dbutil.py 44] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, tb_appid, tb_appname, tb_secret, tb_token
[2018-11-14 15:32:58,798 ERROR 41180 dbutil.py 44] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, tb_appid, tb_appname, tb_secret, tb_token
[2018-11-14 15:33:12,727 ERROR 13300 dbutil.py 44] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, tb_appid, tb_appname, tb_secret, tb_token
[2018-11-14 15:33:25,652 ERROR 37340 dbutil.py 44] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, tb_appid, tb_appname, tb_secret, tb_token
[2018-11-14 15:33:47,524 ERROR 41072 dbutil.py 44] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, tb_appid, tb_appname, tb_secret, tb_token
[2018-11-14 15:34:37,984 ERROR 36928 dbutil.py 44] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, tb_appid, tb_appname, tb_secret, tb_token
[2018-11-14 15:35:45,888 ERROR 41200 dbutil.py 44] - Cannot resolve keyword 'wx_appname' into field. Choices are: id, tb_appid, tb_appname, tb_secret, tb_token
[2018-11-14 16:25:50,764 ERROR 43032 dbutil.py 65] - (2003, "Can't connect to MySQL server on '118.89.18.234' (timed out)")
[2018-11-16 17:44:56,462 WARNING 58504 base.py 152] - Not Found: /index
[2018-11-16 17:44:56,717 WARNING 58504 base.py 152] - Not Found: /favicon.ico
[2018-11-16 17:53:17,960 ERROR 60200 exception.py 135] - Internal Server Error: /index
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\python\webchat\core\viewshop\shop_sel_lib.py", line 17, in shop_sel_lib_list
    return render(request,"index.html",{'shoplist':shoplist})
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\template\base.py", line 486, in parse
    raise self.error(token, e)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\template\base.py", line 484, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\django\template\base.py", line 700, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '["category"]' from 'shoplist["category"]'
[2018-11-16 17:53:19,011 WARNING 60200 base.py 152] - Not Found: /favicon.ico
[2018-11-16 17:58:27,289 ERROR 55124 dbutil.py 65] - settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
